# Basic Information 
title: Xinting Hu
position: Postdoctoral Researcher
affiliation: HongKong University
affiliation_link: https://www.hku.hk/
affiliation_logo: ./assets/img/illinois.svg
email: xinting001@e.ntu.edu.sg

# Search Engine Optimization (SEO)
keywords: xinting hu, hu xinting, xintinghu, huxinting
#canonical: https://yaoyaoliu.web.illinois.edu
description: Xinting Hu is a postdoctoral researcher at the University of Hong Kong. Her research lies in equip machines with open-world capabilities for perceiving, understanding, and reconstructing the visual world.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=o6h6sVMAAAAJ
github_link: https://github.com/JoyHuYY1412 
linkedin: https://www.linkedin.com/in/xinting-hu-88a776b4/
twitter: https://x.com/kaleidudu?s=21

# Images 
#avatar: https://img.yliu.me/avatar_new.jpg
avatar: ../assets/profile.png

# Footnotes
footnote: This homepage is adapted from Yaoyao's template. Thanks for sharing the source code!
footnote_link: https://yaoyaoliu.web.illinois.edu/

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 1NCNGPZpDcKbLu1J8u38hbtnjNGGr4a0fX3CBo7zRP4

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
