# Basic Information 
title: Xin Lin
position: Ph.D. candidate
affiliation: Hong Kong Polytechnic University
affiliation_link: https://www.polyu.edu.hk/
affiliation_logo: ./assets/img/illinois.svg
email: 22040745r@connect.polyu.hk

# Search Engine Optimization (SEO)
keywords: Xin Lin, Lin Xin, xinlin, linxin
#canonical: https://yaoyaoliu.web.illinois.edu
description: Xin Lin is a final-year Ph.D. candidate at The Hong Kong Polytechnic University.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
#google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=o6h6sVMAAAAJ
github_link: https://github.com/xinlin-me/ 
#linkedin: https://www.linkedin.com/in/xinting-hu-88a776b4/
#twitter: https://x.com/kaleidudu?s=21

# Images 
#avatar: https://img.yliu.me/avatar_new.jpg
avatar: ../assets/profile.png

# Footnotes
footnote: This homepage is adapted from Yaoyao's template. Thanks for sharing the source code!
footnote_link: https://yaoyaoliu.web.illinois.edu/

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: Xx_YP3xjGGhocDa_a32OfoHy_p0syWe1y-2ZVOqiUIA

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
